import { Component, OnInit } from '@angular/core';
import { Button2Component } from '../shared/components/button-2/button-2.component';

interface Person {
  fullName: string;
  isTyping: boolean;
  isBadge: boolean;
  isSelected: boolean;
  isBlinking: boolean;
}

@Component({
  selector: 'app-luck',
  templateUrl: './luck.component.html',
  styleUrls: ['./luck.component.scss'],
})
export class LuckComponent implements OnInit {

  randomParticipants: Person[] = [];

  people: Person[] = [
    { fullName: 'Infantes Sébastien', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Marc-Eric Basse', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jeremy Lesert', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'François Caus', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mickael DAVID', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Marc Lagroy de Croutte', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Guillaume Deligne', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'DJAFAR Johan', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Quentin Violleau', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Wassim Bouzazi', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'CHABIN Florent', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Amandine Portier', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Alexandre GREGOIRE', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Bruno POYAC', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Judicaël Pontet', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Buczek Jonathan', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Valentin Carle', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Nicolas Garciau', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Fakir Ismaël', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Christian Margris', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Thibault Roux', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jérôme Lartaud', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Damien Belliard', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Nicolas LE COZ', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jeremy LAFFORGUE', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Huet Jean-Philippe', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'LAINE FABRICE', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Cyril Epinat', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'MERIGAULT Estelle', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Fauny Valentin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Cyril DERRIEN', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Romain Marie', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Romain Cahuet', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'AVARELLO Guillaume', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'BATY Simon', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Matthieu Mignot', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'AUDRIN Philippe', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lepretre Ludovic', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Tony Delalande', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'THIBAULT LOMENEDE', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'François Stricher', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Alexandre Guillemot', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Olivier CARALP', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Dominique Jaafar', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Bertrand Kaczmarek', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Blanc Rémi', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'TEIGNE Hugo', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Victor Vogel', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: "Prosper N'Guessan", isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Romain Querleu', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Olivier Bailly', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'NICOLAS CLEMENT', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mathiot Antoine', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Schlosser Frédéric', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mickaël Zanardo', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Hochez Corentin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Vincent Sébastien', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Vincent Fromont', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Michel Dorian', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Duplouich Nicolas', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Miftah Mustapha', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Dervogne Véronique', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Timothée MULLER', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'GUILLAUME Alexandre', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Samson F. Perret', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mireille LIPP', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'RISTORD CÉDRIC', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Corentin Gardies', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Benjamin BOUR', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'GELLYNCK MATHIEU', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Florian MARI', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Pierre Jauneau', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Ammouri Soufiane', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'HERBAUX Sébastien', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Vincent LE MOUAL', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Boris Falempin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Benoît Drochon', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Guillaume Deysine', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Baptiste Bailly', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Sylvain Chupin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'SEURAT Samuel', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Loann Menard', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Francis Lachand', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Arthur Debono', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Charly Chevillon', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'DROUET Rodolphe', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Arnaud CARADANT', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'SEMENT Morgan', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Esteves Pereira Nicolas', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Marc Gadé', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Thibaut HEYNARD', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jérôme Nieruchalski', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'ARNOS Eric', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lout Alexis', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Pierre Oswald', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Martin Chevalier', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'William Groc', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'François Bichot', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Laurent Bourdeau', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Théo Mira', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Vaiolini TRAVERS', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Adrien Mourgout', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'JOSEPH Selven', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Romain Scaillierez', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Samuel GIRARD', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'TILLIER Benoit', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Braem Berenger', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Germain Guillaume', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Tougeron Rafael', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'GUYARD THOMAS', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Dastugue Julien', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'RIZK Camille', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Fandos Francisco', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Thomas THEVENET', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Guy AUDUREAU', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Xavier Bodenand', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Yoan ROHR', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Troël Yann', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Julien Vigues', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Eloi JONIK', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Eric Fonteneau', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lapierre Victor', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Richard Alexandre', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'TEMMERMAN Thomas', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: "Faivre d'Arcier Etienne", isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Brevet Gwenaëlle', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Robin Debart', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Bubreg Julien', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Laurent DE SADELEER', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Duvernois Loïc', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Coline Mazars', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'EVRARD Lucas', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Nicolas Lafitte', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Titouan Roos', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Kim Maroé', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jean-Pierre KUNTZ', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Geoffrey Sarraud', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Matthias Varlet', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Roux Jean-Marc', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Romain Florian', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jerome PRUM', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lucas Noffray', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Moenne-Loccoz Tom', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Nicolas Lecestre', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Constant Faidherbe', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Escaille Bastien', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'ROUSSEAU Clément', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mael Desdoits', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Dimitry Helman', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Leopold Harmand', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Casciaro Cyril', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lebois Kevin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Stéphane Bui-Phuong', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Christophe DEURVEILHER', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Nicolas Dussueil', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Léo Etienne', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Philippe Dreyer', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Dimitri Martin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Hingray', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Alexandre Bailleul', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Brandon Imbert', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jonathan FLAHAUT', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Anthony Pena', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Sam Hope', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Timéo Lebot', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Dusconi Jeremy', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Bonnin Marc-Anthony', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Thomas Vallas', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Fabien Arnaud', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jonathan Rousselot', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Rémy Dekeister', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lambert Yoann', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lorenzo Bucovaz', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Claude Martinez', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Kévin Jung', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lou-Anne Lambert', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Etienne Desbordes', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Marie Cayer-Barrioz', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Tony Pallaruelo', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Loic Maitre', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Garcia Alexis', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Maxence Caceres', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Chloé Almanza', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Boisseranc Kevin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Aboudaram Eric', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Samin David', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'DEMINGEON Adrien', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Maël NICOLAZO', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Guilloineau Johan', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Thibault Bride', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Julien Trolet', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Julien Studer', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Benjamin Oudin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'FARGES Cyriac', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Zapata Thomas', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Maxence Maho', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'BRACHET Benjamin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Christophe PLISSIER', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Laurent Van Rompu', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'MOUGENOT Noël', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Boughlita Tarek', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Alexandre Franquet', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Vincent CHAMPSIAUX', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'REQUET François', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Fleury Julien', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Gammelin Anthony', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Julien Louis-Paul', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Hadrien Lanneau', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Alexandre Bruneau', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Yoann Lagache', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Borjon Piron Nathalie', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Nicolas Elmer', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Vivien FEAT', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'David Perry', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lucas CORNU', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Arthur BATARD', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Raphael KAHN', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Schmisser Denis', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Muel Kévin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Fouchier Denis', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Pierre Novacovici', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Ange Stoianov', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Luc Pizzuti', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Kevin Cornanguer', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jonathan COTTREL', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jules Pereira Macedo', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Maxime Adam', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Alexis ROEGIS', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Arnaud BEAUDOUIN', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'GOMIERO Bruno', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Maud KEREBEL', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mathias BOISGARD', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Romain Tello', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Julien MERLIN', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Adrien Servel', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Luc Fournier-Comte', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Fabien Banci', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Osman Baiteche Jacquemin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Maxime Bayle', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Laure Mollo Gautier Richard', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Aurèle Tesson', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Florent Della Valle', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Pons Stephanie', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'MACÉ Benjamin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Florence Gautier', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'LAQUENAIRE JEAN-BAPTISTE', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Guillaume Infantes', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'MENNE Thomas', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Thomas Ciampossin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'JENVRIN Jerome', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Michaël Louveau', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jeremy Telliet', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Benoit Tabuteau', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Maxime Laurent', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'LALOUZE DAVID', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Guillaume JACQUE', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Simon Hardouineau', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lamblin Miguel', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'BENCHABANE Nicolas', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Didier Mellinger', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Genou Sten', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Gregory BLANC', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Yan LAMBERT', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mevel Régis', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Thibaut NGUYEN', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Ludovic Ovsepian', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Zakaria Belaziz', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Hauguel Cyriaque', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Stefen Gueguen', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Inès FERRI', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Paul-Hervé GAUTRON', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Thibault Douilly', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'MAGOAROU Stephane', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'HIVERT Pascal', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'TAMAGNI MATHIAS', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'ALEXIS SAUVAGE', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Gwenael Maurize', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Xavier Cheney', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Yoann Fagot', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Hein Lucile', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Coline Hennequin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Renon Mathieu', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jonathan Jacques', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'ZERMATI FRANCOIS', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Besson Erwan', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'BROUSSE WILLIAM', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jérémy Thomas', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Hurtis Aurele', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Obermosser Bastien', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Bruno Filoche', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jean-François RENAULD', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Simo Sudre', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Denis GUILLANEUX', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mignot Mickaël', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Axel Le Maitour', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Chauvey John-Alexander', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Nicolas BERNARD', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Charles Gibault', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mathieu CATTIN', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Guillaume OLLIVIER', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Pascal DUMONT', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Raphaël Fouilloux', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Cyril JOLY', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Benoît GUELIN', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'HENRION Jean-Baptiste', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Maël BOUTIN', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Assaf Hirsch', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Menauge Christophe', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lucas AZAIS', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Félix Humbaire', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Foucault Nicolas', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'M. Dorian STOLS', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'DE TAXIS DU POËT Rémi', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Antonin FLEURY', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Clément BRAU', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'DENIS Laurent', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Cyril Provost', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Julien Wintzer', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Ronan RABASSE', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Cyril Pruneau', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Cyrill De giuseppe', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Pablo Lopez Rodriguez', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Petr Mochow', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Simon arthur', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Martin Wolf', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Julia Grützner', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Matteo Dodero', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Richard Paul', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Alexey Timakov', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Eurlings Frédéric', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Marco Villaggi', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Frédéric Borzee', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Alain Guinand', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Benoit De Munck', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mattias Mörner', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Andrew Keel', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Thomas Rossié', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Gregorio Console', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Michael Koerbis', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Joaquin Grau', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mariam Jaafar Holmlund', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Max Stone', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Marc van Westen', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Edoardo Sciaroni', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'ANRIANNE Valentin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Ian Pardo', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Nicolas Davin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Martin Will', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Siudak Stephan', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Richard El-chamaa', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Javier Vazquez Juan', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Barry Austin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Robert Lötberg', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Tine Mauer', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Christian Nord', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Sam Joachim', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Michał Kopystecki', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Louis hogge', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Davide Quaglia', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Federico Farina', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Ulf Nuernberg', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Elodie Houssiere', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Veit Moeller', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Tobias Anton', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Benjamin Kirk Brightwell', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Liam Cox', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Eetu Kahelin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Blair Sorbie', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jens Thorup Rasmussen', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lai BSNHSTJE', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Coen van der Wel', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'David Eitz', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Ferah Sherifov', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Tom Hinsley', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Andrea Giannatempo', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Igor Bodrov', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Artur Biesiadowski', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Gian Heimann', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'PUJAT Brice', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Alexander Alig', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Pavla Zbořilová', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Giedrius Lescinskas', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Martin-Ullrich Dittmer', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Luiz Carlos Soares', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'S Dinjens', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Gunnar Krutå Dalen', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Dominik Laffer', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Giuseppe De Carolis', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Stéphan Leidinger', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Giuseppe Lain', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'POLLINA Mike', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Thomas Petereit', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Isaac Martinez', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'levieux jerome', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Vesa-Matti Sarenius', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Robertas Kuzminskas', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Thorsten Stein', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jacob Krämer', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Joachim Bastin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'alejandro carrascosa saenz', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'My Nguyen', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Victor Jéquier', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Benjamin Raible', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Maikel Luts', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Simon Hicks', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Cedric Fraselle', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Casper Stig Bondesen', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mattis Bohnet', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Rasmus Nilsen', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Vilmantas Juras', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jan Höffken', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Oliver Powroznik', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Nicolas Molron', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Tommaso Cirelli', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Timothy Crittenden', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Toni Kuikka', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Miller Laurent', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Pieter Van der Haegen', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Hannes Brugger', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mateusz Tarnaski', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Scott Holme', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Papp Kristóf', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Paolo BETTANIN', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Giovanni Lorenzo', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Petr Michalec', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Hiba El Banouti', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Ties Haverkate', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Grenzpaket Pilss', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Dennis Kamm', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Sandow Dieter', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Emiliyan Ivanov Simeonov', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Benjamin Gademann', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Kilian Zurkinden', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Anthelme Rochaix Yamamoto', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Enrico Tomasi', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Christian Trachsel', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Sebastien Pollet', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Primoz Noe', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Marko Strittmatter', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'DONATAS JURAS', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Gautier Devuyst', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Nicolas Bragard', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Anna Iklody', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Stipe Filipi', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'romain billion', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Ciobanu Andrei', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Ruari Scott', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jamie Holloway', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Weega srl - Roberto Romanelli', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Stefan Buster', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Miguel Gregoire', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Heiko Walldorf', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'TIM CLAYTON', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Andre Mueller', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Kenneth Janssen', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Noé Famelart', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Tomas Davidek', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Kaino Lagoni', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mario Hofmann', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Massimo Montanari', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Michael Hubert', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mads Rivals Hansen', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Michele Aleandri', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jannik Bücher', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Matthias Andree', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Tom Quinders', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Andy Pauer', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Thomas Andree', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Andrew Daly', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Matteo Dodero', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Stephan Grundner', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Oscar Williams', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lukas Dreyling', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Ruben Bardok', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Kaur Reidma', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Florian Nerz', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Dennis Behl', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Luca Gutzeit', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Dejoie Jean-Francois', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Téophile Bruggimann', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Tristan Malotiaux', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Tschanz Kevin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Nick Wilson', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Daniel Sandor Nyika', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Julia Grützner', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Steven Salwetzke', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Alexander Weickmann', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Christian Thelen', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Andrei Adamov', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Arkadiusz Gurba', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Björn Sönke Lange', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'simone loffredo', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Sean Martin', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: "Worlds' End Comics & Games", isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lukasz Szymanski', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Wiktor Woźniak', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jan-Niklas Dörr', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Edd Langridge', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Nathan Hubens', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Victor Ortiz', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Fabio Nigro', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Louis J Meredith', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Stefanie Brenner', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Kim Reynolds', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Ronny Ludwig', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Thomas Meinke', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Jonathan favaits', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Matteo Furlan', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Emilio Pierotti', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Alexander Lauth', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Gabriel Wagner', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Pierre Paugam', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Bert Moors', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Bíró Ádám', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Tim Michiels', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Predrag Bajic', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Bartosz Chajdecki', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Mark J Hills', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Fons de Vogel', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Bodnár Tamás', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: "Sven D'Hondt", isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Yiannis Thomopoulos', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lukas Foltyn', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'kapageridis', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Floriane Rader', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Ahmad aslam', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Christophe Gordenne', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Marcos Bento', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Rafael Jerez Molinero', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Marian Weirich', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'William Polet', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Vincent Defêche', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Peter Geudens', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Lauer Guillaume', isTyping: false, isBadge: false, isSelected: false, isBlinking: false },
    { fullName: 'Filip Loguin Hjärne', isTyping: false, isBadge: false, isSelected: false, isBlinking: false }
  ];

  isAnimationStarted = false;
  showWinnerOverlay = false;
  winner: Person | null = null;

  ngOnInit() {
    // Supprimez l'appel automatique de startTypingAnimation()
    this.randomParticipants = this._selectRandomParticipants();
  }

  async startTypingAnimation() {
    if (this.isAnimationStarted) return;
    this.isAnimationStarted = true;

    for (let i = 0; i < this.randomParticipants.length; i++) {
      this.randomParticipants[i].isTyping = true;
      await this.delay(100); // Réduit de 1000ms à 100ms
      this.randomParticipants[i].isTyping = false;
      this.randomParticipants[i].isBadge = true;
    }
  }

  private _selectRandomParticipants(): Person[] {
    // Copie du tableau original pour ne pas le modifier
    const shuffledPeople = [...this.people]
      // Algorithme de Fisher-Yates pour mélanger le tableau
      .sort(() => Math.random() - 0.5)
      // Prendre les 25 premiers éléments
      .slice(0, 30);
      
    return shuffledPeople;
  }

  async startLottery() {
    if (!this.randomParticipants.every(p => p.isBadge)) {
      await this.startTypingAnimation();
      await this.delay(500);
    }
    
    for (let i = 0; i < 30; i++) {
      this.randomParticipants.forEach(p => p.isBlinking = false);
      const randomIndex = Math.floor(Math.random() * this.randomParticipants.length);
      this.randomParticipants[randomIndex].isBlinking = true;
      await this.delay(100);
    }

    this.randomParticipants.forEach(p => p.isBlinking = false);
    
    this.winner = this.randomParticipants[Math.floor(Math.random() * this.randomParticipants.length)];
    this.winner.isSelected = true;
    
    // Afficher l'overlay après un court délai
    await this.delay(500);
    this.showWinnerOverlay = true;
    
    // Optionnel : Fermer l'overlay après quelques secondes
    setTimeout(() => {
      this.showWinnerOverlay = false;
    }, 5000);
  }

  private delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}
